# Generated by Django 5.0 on 2025-01-17 11:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("izr_media", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("title_ar", models.CharField(blank=True, max_length=255, null=True)),
                ("enabled", models.BooleanField(default=True)),
                ("flyer", models.ImageField(upload_to="izr_media/")),
                ("flyer_ar", models.ImageField(upload_to="izr_media/")),
                ("flyerTV", models.ImageField(upload_to="izr_media/")),
                ("subtitle", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "subtitle_ar",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField()),
                ("description_ar", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Gallery Title"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Gallery Description"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Hadith",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_ar", models.CharField(max_length=255)),
                ("data_de", models.CharField(max_length=255)),
                ("hadith_ar", models.TextField()),
                ("hadith_de", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="PrayerCalculationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calculation_angle",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(12),
                            django.core.validators.MaxValueValidator(18),
                        ]
                    ),
                ),
                ("default_longitude", models.FloatField(default="12.102841")),
                ("default_latitude", models.FloatField(default="49.007734")),
            ],
            options={
                "verbose_name": "Prayer Calculation Configuration",
                "verbose_name_plural": "Prayer Calculation Configuration",
            },
        ),
        migrations.CreateModel(
            name="PrayerConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("config_name", models.CharField(max_length=50)),
                ("enabled", models.BooleanField(default=False)),
                ("asr", models.IntegerField(default=15)),
                ("dhuhr", models.IntegerField(default=15)),
                ("fajr", models.IntegerField(default=15)),
                ("isha", models.IntegerField(default=5)),
                ("jumaa", models.IntegerField(default=0)),
                ("maghrib", models.IntegerField(default=5)),
                ("tarawih", models.IntegerField(default=0)),
                ("day_correction", models.IntegerField(default=1)),
                (
                    "ramadan",
                    models.CharField(
                        choices=[("on", "On"), ("off", "Off")],
                        default="off",
                        max_length=3,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prayer Config",
                "verbose_name_plural": "Prayer Configurations",
            },
        ),
        migrations.CreateModel(
            name="Statement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("about_us", "Über Uns"),
                            ("statement", "Stellungnahme"),
                        ],
                        default="about_us",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("os", models.CharField(max_length=50)),
                ("token", models.TextField()),
                ("test2", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ContentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("header", "Header"),
                            ("paragraph", "Paragraph"),
                            ("image", "Image"),
                        ],
                        max_length=50,
                    ),
                ),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="blog_images/"),
                ),
                (
                    "v_image",
                    models.BooleanField(default=False, verbose_name="Vertical Image"),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_items",
                        to="izr_media.blog",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="gallery_images/", verbose_name="Upload Image"
                    ),
                ),
                (
                    "is_vertical",
                    models.BooleanField(default=True, verbose_name="Is Vertical"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="izr_media.gallery",
                    ),
                ),
            ],
        ),
    ]
