# Generated by Django 5.0 on 2025-01-19 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("izr_media", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prayercalculationconfig",
            name="calculation_angle",
        ),
        migrations.AddField(
            model_name="prayercalculationconfig",
            name="fjar_angle",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(12),
                    django.core.validators.MaxValueValidator(18),
                ],
            ),
        ),
        migrations.AddField(
            model_name="prayercalculationconfig",
            name="isha_angle",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(12),
                    django.core.validators.MaxValueValidator(18),
                ],
            ),
        ),
        migrations.AddField(
            model_name="prayercalculationconfig",
            name="jumaa_time",
            field=models.TimeField(default="12:00"),
        ),
        migrations.AddField(
            model_name="prayercalculationconfig",
            name="tarawih_time",
            field=models.TimeField(default="12:00"),
        ),
        migrations.AlterField(
            model_name="prayercalculationconfig",
            name="default_latitude",
            field=models.FloatField(default=49.007734),
        ),
        migrations.AlterField(
            model_name="prayercalculationconfig",
            name="default_longitude",
            field=models.FloatField(default=12.102841),
        ),
    ]
