# Generated by Django 5.0 on 2025-03-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("izr_media", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description_en",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="event",
            name="flyerTV_ar",
            field=models.ImageField(
                default="izr_media/default.jpg", upload_to="izr_media/"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="flyerTV_en",
            field=models.ImageField(
                default="izr_media/default.jpg", upload_to="izr_media/"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="flyer_en",
            field=models.ImageField(
                default="izr_media/default.jpg", upload_to="izr_media/"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="subtitle_en",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="event",
            name="title_en",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="event",
            name="description_ar",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="event",
            name="flyer",
            field=models.ImageField(
                default="izr_media/default.jpg", upload_to="izr_media/"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="flyerTV",
            field=models.ImageField(
                default="izr_media/default.jpg", upload_to="izr_media/"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="flyer_ar",
            field=models.ImageField(
                default="izr_media/default.jpg", upload_to="izr_media/"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="subtitle",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="subtitle_ar",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="title_ar",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
