# Generated by Django 5.0 on 2025-01-19 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("izr_media", "0003_remove_prayercalculationconfig_calculation_angle_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prayercalculationconfig",
            old_name="fjar_angle",
            new_name="fajr_angle",
        ),
    ]
