# Generated by Django 5.0 on 2025-03-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("izr_media", "0003_event_description_en_event_flyertv_ar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="more_info",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(
                blank=True, default="", verbose_name="Description (German)"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="description_ar",
            field=models.TextField(
                blank=True, default="", verbose_name="Description (Arabic)"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="description_en",
            field=models.TextField(
                blank=True, default="", verbose_name="Description (English)"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="enabled",
            field=models.BooleanField(default=True, verbose_name="Event Enabled"),
        ),
        migrations.AlterField(
            model_name="event",
            name="flyer",
            field=models.ImageField(
                upload_to="izr_media/", verbose_name="Flyer (German)"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="flyerTV",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="izr_media/",
                verbose_name="Flyer TV (German)",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="flyerTV_ar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="izr_media/",
                verbose_name="Flyer TV (Arabic)",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="flyerTV_en",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="izr_media/",
                verbose_name="Flyer TV (English)",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="flyer_ar",
            field=models.ImageField(
                null=True, upload_to="izr_media/", verbose_name="Flyer (Arabic)"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="flyer_en",
            field=models.ImageField(
                null=True, upload_to="izr_media/", verbose_name="Flyer (English)"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="subtitle",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Subtitle (German)"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="subtitle_ar",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Subtitle (Arabic)"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="subtitle_en",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Subtitle (English)",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title (German)"),
        ),
        migrations.AlterField(
            model_name="event",
            name="title_ar",
            field=models.CharField(
                default="", max_length=255, verbose_name="Title (Arabic)"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title_en",
            field=models.CharField(
                default="", max_length=255, verbose_name="Title (English)"
            ),
        ),
    ]
