# Generated by Django 5.0 on 2025-01-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("izr_media", "0004_rename_fjar_angle_prayercalculationconfig_fajr_angle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prayerconfig",
            name="day_correction",
        ),
        migrations.RemoveField(
            model_name="prayerconfig",
            name="ramadan",
        ),
        migrations.RemoveField(
            model_name="prayerconfig",
            name="tarawih",
        ),
        migrations.AddField(
            model_name="prayercalculationconfig",
            name="correction_day",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="prayercalculationconfig",
            name="ramadan",
            field=models.CharField(
                choices=[("on", "On"), ("off", "Off")], default="off", max_length=3
            ),
        ),
    ]
