# Generated by Django 5.0 on 2025-03-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("izr_media", "0004_event_more_info_alter_event_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calculationmethod",
            name="method_id",
        ),
        migrations.AddField(
            model_name="calculationmethod",
            name="name_ar",
            field=models.CharField(default="", max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name="calculationmethod",
            name="name_de",
            field=models.CharField(default="", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="calculationmethod",
            name="name",
            field=models.CharField(default="", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="calculationmethod",
            name="short_name",
            field=models.CharField(default="", max_length=50, unique=True),
        ),
    ]
