# Generated by Django 5.0 on 2025-10-22 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("izr_media", "0005_remove_calculationmethod_method_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prayercalculationconfig",
            name="fajr_angle",
            field=models.FloatField(
                default=18.0,
                validators=[
                    django.core.validators.MinValueValidator(12),
                    django.core.validators.MaxValueValidator(19),
                ],
            ),
        ),
    ]
