# Generated by Django 5.0 on 2025-01-19 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("izr_media", "0005_remove_prayerconfig_day_correction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prayercalculationconfig",
            name="jumaa_time",
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AlterField(
            model_name="prayercalculationconfig",
            name="tarawih_time",
            field=models.TimeField(default=datetime.time(20, 30)),
        ),
    ]
