# Generated by Django 5.0 on 2025-01-19 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("izr_media", "0006_alter_prayercalculationconfig_jumaa_time_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prayercalculationconfig",
            options={
                "verbose_name": "Prayer Times Calculations",
                "verbose_name_plural": "Prayer Times Calculations",
            },
        ),
    ]
