# Generated by Django 5.0 on 2025-10-22 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("izr_media", "0006_alter_prayercalculationconfig_fajr_angle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prayercalculationconfig",
            name="isha_angle",
            field=models.FloatField(
                default=18.0,
                validators=[
                    django.core.validators.MinValueValidator(12),
                    django.core.validators.MaxValueValidator(19),
                ],
            ),
        ),
    ]
