# Generated by Django 5.0 on 2025-01-19 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("izr_media", "0007_alter_prayercalculationconfig_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prayerconfig",
            options={
                "verbose_name": "Iqama Times",
                "verbose_name_plural": "Iqama Times",
            },
        ),
    ]
