# Generated by Django 5.0 on 2025-02-17 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("izr_media", "0008_alter_prayerconfig_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="prayercalculationconfig",
            name="asr_tune",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="prayercalculationconfig",
            name="dhuhr_tune",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="prayercalculationconfig",
            name="fajr_tune",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="prayercalculationconfig",
            name="imsak_tune",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="prayercalculationconfig",
            name="isha_tune",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="prayercalculationconfig",
            name="maghrib_tune",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="prayercalculationconfig",
            name="midnight_tune",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="prayercalculationconfig",
            name="sunrise_tune",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="prayercalculationconfig",
            name="sunset_tune",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="prayercalculationconfig",
            name="fajr_angle",
            field=models.FloatField(
                default=18.0,
                validators=[
                    django.core.validators.MinValueValidator(12),
                    django.core.validators.MaxValueValidator(18),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="prayercalculationconfig",
            name="isha_angle",
            field=models.FloatField(
                default=18.0,
                validators=[
                    django.core.validators.MinValueValidator(12),
                    django.core.validators.MaxValueValidator(18),
                ],
            ),
        ),
    ]
