# Generated by Django 5.0 on 2025-02-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("izr_media", "0009_prayercalculationconfig_asr_tune_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prayercalculationconfig",
            name="correction_day",
        ),
        migrations.AddField(
            model_name="prayercalculationconfig",
            name="config_name",
            field=models.CharField(
                default="Prayer Times Config of The Islamic Center of Regensburg",
                max_length=50,
            ),
        ),
    ]
