# Generated by Django 5.0 on 2025-02-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("izr_media", "0010_remove_prayercalculationconfig_correction_day_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalculationMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("method_id", models.IntegerField(unique=True)),
            ],
            options={
                "verbose_name": "Calculation Method",
                "verbose_name_plural": "Calculation Methods",
            },
        ),
    ]
