# Generated by Django 5.0 on 2025-02-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("izr_media", "0012_calculationmethod_short_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculationmethod",
            name="short_name",
            field=models.CharField(default="", max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="calculationmethod",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
