# Generated by Django 5.0 on 2025-03-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("izr_media", "0013_calculationmethod_short_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prayercalculationconfig",
            name="correction_day",
            field=models.IntegerField(default=0),
        ),
    ]
