# Generated by Django 5.0 on 2025-03-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("izr_media", "0014_prayercalculationconfig_correction_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="prayercalculationconfig",
            name="calculation_type",
            field=models.CharField(
                choices=[
                    ("static", "Static (use fixed angles)"),
                    ("dynamic", "Dynamic (use dynamic angle)"),
                ],
                default="static",
                max_length=50,
            ),
        ),
    ]
