name: Build and Push Docker Image

on:
  push:
    branches:
      - main # trigger only on main branch merges

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Define version (using run number + short commit sha)
      - name: Set image version
        id: vars
        run: |
          VERSION="${GITHUB_RUN_NUMBER}-${GITHUB_SHA::7}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/izr-backend:${{ steps.vars.outputs.version }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/izr-backend:${{ steps.vars.outputs.version }} ${{ secrets.DOCKER_USERNAME }}/izr-backend:latest

      # Push Docker image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/izr-backend:${{ steps.vars.outputs.version }}
          docker push ${{ secrets.DOCKER_USERNAME }}/izr-backend:latest
